#!/bin/bash
LANGUAGE=$1
VIDEO=$2

OIFS="$IFS"
IFS=$'\n'

FILENAME=$(basename "$VIDEO")
EXTENSION=${FILENAME##*.}
FILENAME_WITHOUT_EXTENSION=${FILENAME%.*}
VIDEO_WITHOUT_EXTENSION=${VIDEO%.*}
VIDEO_WITHOUT_EXTENSION=$(printf '%q' "$VIDEO_WITHOUT_EXTENSION")

if [ -n "$LANGUAGE" -a "$LANGUAGE" != " " ] ; then
	SUBTITLE="$VIDEO_WITHOUT_EXTENSION*$LANGUAGE"*.srt
else
	SUBTITLE="$VIDEO_WITHOUT_EXTENSION"*.srt
fi

SUBTITLE_FOUND=$(ls $SUBTITLE 2> /dev/null)
[ -z "$SUBTITLE_FOUND" ] && echo $VIDEO

IFS="$OIFS"